### PR TITLE
Affine transformation support

### PR DESCRIPTION
**Pull request by kmatzen**
This wraps ```MagickAffineTransformImage``` which provides convert's -affine functionality.

### CODE REVIEW

**Comment by soumith** [comment]
very cool. thanks!

**Comment by kmatzen** [comment]
After using this a bit, I came across a bug in GraphicsMagick.  Depending on your affine matrix, their implementation might fail.  I've filed a ticket.
https://sourceforge.net/p/graphicsmagick/bugs/316/

**Comment by soumith** [comment]
as an alternative, you can use image.warp which is bug-free.

**Comment by nicholas-leonard** [comment]
@kmatzen could you PR some docs?

**Pull request merged**
