### PR TITLE
error: fix double free (load) and print details

### PR DESCRIPTION
**Pull request by deltheil**
If an error occurred, the call to `clib.DestroyMagickWand(self.wand)` at load time is not required since a finalizer has already been hooked up at `Image.new` time:

```Lua
image.wand = ffi.gc(clib.NewMagickWand(), function(wand)
  -- Collect:
  clib.DestroyMagickWand(wand)
end)
```

This caused double free errors or core dumped.

Note: I have also improved the error reporting with the description and severity code from GM, e.g:

```
magick.Image: error loading image: Unable to open file (city-corrupt.jpg) (ExceptionType=430)
```

### CODE REVIEW

**Comment by soumith** [comment]
nice! This has always annoyed me with this package. Finally it's fixed.

**Comment by deltheil** [comment]
@soumith glad you did not merge it yet: I just pushed an additional commit that **do** free the memory returned by `MagickGetException`. At first I got fooled by this wrong cdef:

```C
/* WRONG! This function returns a `char *` */
const char* MagickGetException(const MagickWand*, ExceptionType*);
```

I have fixed the cdef in addition. Let me know if you have any remark before merging.

**Comment by soumith** [comment]
I don't have merge rights for this repo. Its all clement

**Comment by clementfarabet** [comment]
Cool, that helps!

**Pull request merged**
